// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZw-p99fOaev-ZLpsZdsU5-ri3O5diaU',
    appId: '1:394691029555:android:b098c6920847b687cc1146',
    messagingSenderId: '394691029555',
    projectId: 'milkyway-app-f0848',
    storageBucket: 'milkyway-app-f0848.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9dLOe5a3HwdMzjULgrMBNsbPGL183Q-8',
    appId: '1:394691029555:ios:e9daa214413e3d79cc1146',
    messagingSenderId: '394691029555',
    projectId: 'milkyway-app-f0848',
    storageBucket: 'milkyway-app-f0848.firebasestorage.app',
    androidClientId: '394691029555-ju919mhi6d95k5isn1k1ek8a0e1c8ud1.apps.googleusercontent.com',
    iosClientId: '394691029555-cbbjdf7io2tec9004t3b31ons9r0a2g3.apps.googleusercontent.com',
    iosBundleId: 'com.whatif.milkyway',
  );

}